title: The life is REAL  # 원하는 제목으로 변경
author: bbjoony  # 본인 이름으로 변경
email: bbjoony@gmail.com  # 본인 이메일로 변경
description: > 
  중년의 게임QA 
  Google 검색 결과와 RSS 피드에 표시됩니다.
show_excerpts: true

# Build settings
remote_theme: samarsault/plainwhite-jekyll

# Theme configuration
plainwhite:
  name: bbjoony  # 본인 이름으로 변경
  tagline: game QA  # 원하는 태그라인으로 변경
  date_format: "%b %-d, %Y"
  sitemap: true
  search: true
  dark_mode: true
  html_lang: "ko"  # 한국어 사이트라면 "ko"
  
  # 소셜 링크 (사용하지 않는 것들은 주석 처리하거나 삭제)
  social_links:
    github: bbjoony  # 본인 GitHub 아이디
    twitter: bbjoony
    linkedIn: https://www.linkedin.com/in/seokjun-jin-05215a48/
    email: bbjoony@gmail.com 

plugins:
  - jekyll-seo-tag
  - jekyll-feed
