title: The life is REAL
author: bbjoony
email: bbjoony@gmail.com
description: > 
  중년의 게임QA가 기록하는 일상과 업무 이야기.

# GitHub Pages 기본 테마
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 기본 설정
show_excerpts: true
